test git-lecture.md
hhiro0403/RaiseTech pull request #11
Opened 2024-01-06 03:47 UTC by hhiro0403

課題10の報告テスト

2024-01-07 11:29 UTC, MasatoshiMizumoto requested changes
提出ありがとうございます！
課題達成としては問題ありませんが、テンプレートの実装についてコメントを入れましたのでご対応ください！

2024-01-07 11:29 UTC, MasatoshiMizumoto commented on lecture10 template file/lecture10-alb.inport.yaml
> +       - {'Fn::ImportValue': 'PublicSecurityGroup'}
これはJSON記法なのでYAMLにする
```suggestion
       - ???
```
組み込み関数の方針として省略記法で書くのかどうかも定めておくこと（Fn、!）

2024-01-07 11:29 UTC, MasatoshiMizumoto commented on lecture10 template file/lecture10-alb.inport.yaml
> +     Protocol: HTTP
Line breakの警告が出ているので出ないようにする
```suggestion
     Protocol: HTTP

```

2024-01-07 11:29 UTC, MasatoshiMizumoto commented on lecture10 template file/lecture10-ec2.inport.yaml
> +      Name: PublicSecurityGroup  # この名前でエクスポートする
何が格納されているのか見て判断つかないので、つくようにする。例えばIDなら以下
```suggestion
      Name: PublicSecurityGroupId  # この名前でエクスポートする
```

2024-01-08 04:14 UTC, hhiro0403 commented
修正完了しました確認お願いします
https://github.com/hhiro0403/RaiseTech/blob/lecture10/lecture10.md

2024-01-08 04:23 UTC, MasatoshiMizumoto requested changes
修正漏れがあるようです！
よろしくお願いします！

2024-01-08 04:23 UTC, MasatoshiMizumoto commented on lecture10 template file/lecture10-alb.inport.yaml
> +     Protocol: HTTP
まだ変わらずのようです！

2024-01-08 04:23 UTC, MasatoshiMizumoto commented on lecture10 template file/lecture10-vpc.outputs.yaml
> +      Name: rdssubnetgroup  # この名前でエクスポートする
これだけ命名規則に整合性がない？
これも何が格納される？
```suggestion
      Name: RdsSubnetGroup  # この名前でエクスポートする
```

2024-01-08 04:23 UTC, MasatoshiMizumoto commented on lecture10 template file/lecture10-ec2.inport.yaml
> +      Name: WebInstance  # この名前でエクスポートする
どんな値が入るのでしょう？
```suggestion
      Name: WebInstance  # この名前でエクスポートする
```

2024-01-08 06:40 UTC, hhiro0403 commented on lecture10 template file/lecture10-vpc.outputs.yaml
> +      Name: rdssubnetgroup  # この名前でエクスポートする
以下に修正
  rdssubnetgroup:
    Value: !Ref rdssubnetgroup  # 作成されたIDを
    Export:
      Name: RdsSubnetGroupMysqlID  # この名前でエクスポートする

2024-01-08 06:41 UTC, hhiro0403 commented on lecture10 template file/lecture10-ec2.inport.yaml
> +      Name: WebInstance  # この名前でエクスポートする
以下に修正
  WebInstance:
    Value: !Ref WebInstance  # 作成されたVPCのIDを
    Export:
      Name: WebInstanceAlbTargetGroupID  # この名前でエクスポートする

2024-01-08 06:42 UTC, hhiro0403 commented
コメント頂いた部分修正しました
rdssubnetgroup:
Value: !Ref rdssubnetgroup # 作成されたIDを
Export:
Name: RdsSubnetGroupMysqlID # この名前でエクスポートする

WebInstance:
Value: !Ref WebInstance # 作成されたVPCのIDを
Export:
Name: WebInstanceAlbTargetGroupID # この名前でエクスポートする

2024-01-08 07:24 UTC, hhiro0403 commented on lecture10 template file/lecture10-alb.inport.yaml
> +     Protocol: HTTP
全yamlファイルの最終行に赤い警告がありましたが無くなりました。
指摘していただいた部分でしょうか？

2024-01-08 07:25 UTC, hhiro0403 commented
コメント頂いた部分修正しました
全yamlファイルの最終行に赤い警告がありましたが無くなりました。

2024-01-08 08:22 UTC, MasatoshiMizumoto approved these changes
LGTM!

2024-01-08 09:44 UTC, merged